### ISSUE TITLE
Issue with installing from source

### ISSUE THREAD

**Issue by joelromanky** [traffic-refinery/traffic-refinery#1]
### What's up?

Hello,
I attempted to use this repo to build the traffic refinery tools from source.
But I am facing an issue with installation of GO.
When installing go with `sudo apt install golang`, it install the previous version of Go (1.13) and I am not able to clone the repo.
I got the following with `go get` command
```
can't load package https://github.com/traffic-refinery/traffic-refinery: no Go files in $GOHOME/src/github.com/traffic-refinery/traffic-refinery
```
If I go ahead and continue installation, I will get an error with `make`
```
#github.com/traffic-refinery/traffic-refinery/internal/network
internal/network/traffic-generator.go:67:14: ip.DstIP.IsPrivate undefined (type net.IP has no field or method IsPrivate)
note: module requires Go 1.16
make: *** [Makefile:2 : all] Erreur 2
```

I try to install Go with instructions on [Go Page](https://golang.org/doc/install). It will install the version 1.18.
But with this, `go get` is deprecated and we must use `go install` instead. This command outputs:
```
go: github.com/traffic-refinery/traffic-refinery@latest: module github.com/traffic-refinery/traffic-refinery@latest found (v0.0.0-20220126095304-2d2217d17f59) but does not contain package github.com/traffic-refinery/traffic-refinery
```

Do you have any solution regarding this ?
Thank you.

PS: I am using Ubuntu 20.04.

### Due diligence

- [X] I have read the docs

**Comment by wontoniii** [comment]
Hello, 
Have you run `go mod tidy` before running `make`? 

Related to `go install`, for the time being, we only included instructions to build the code, i.e., `go build`.

Francesco

**Comment by joelromanky** [comment]
Hello,

Yes, I run `go mod tidy` before running `make`.
There were no errors in the outputs.

**Comment by wontoniii** [comment]
Not sure what is the remaining issue then :) 

If it builds with `make`, the remaining task should be executing the binary. 

Francesco
